#For description of parameter please do refer to Readme.txt
version: '3.7'
services:
  rcs:
    image: registry.opentext.com/dctm-server:${VERSION}
    environment:
      - DOCKER_HOST=${IP}
      - DATABASE_HOST=${IP}
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_SERVER_PORT=5432
      - SERVICE_NAME=MyPostgres
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - INSTALL_OWNER=dmadmin
      - INSTALL_OWNER_PASSWORD=dmadmin
      - DOCBASE_NAME=${REP}
      - GLOBAL_REGISTRY_PASSWORD=${GLOBAL_REGISTRY_PASSWORD}
      - AEK_ALGORITHM=AES_256_CBC
      - AEK_PASSPHRASE=${AEK_PASSPHRASE}
      - AEK_NAME=CSaek
      - CONFIGURE_THUMBNAIL_SERVER=NO
      - THUMBNAIL_SERVER_PORT=8081
      - THUMBNAIL_SERVER_SSL_PORT=8443
      - EXTERNAL_DOCBROKER_PORT=1689
      - CONTENTSERVER_PORT=50000
      - APP_SERVER_PASSWORD=${APP_SERVER_PASSWORD}
      - INSTALL_OWNER_UID=1001
      - HIGH_VOLUME_SERVER_LICENSE=
      - TRUSTED_LICENSE=
      - STORAGEAWARE_LICENSE=
      - XMLSTORE_LICENSE=
      - SNAPLOCKSTORE_LICENSE=
      - RPS_LICENSE=
      - FED_RECD_SERVICE_LICENSE=
      - RECORD_MANAGER_LICENSE=
      - PRM_LICENSE=
      - DOCBASE_PASSWORD=${DOCBASE_PASSWORD}
      - INSTALLER_UI=silent
      - KEEP_TEMP_FILE=false
      - INSTALLER_DEBUG_LOG=true
      - DOCBASE_ID=453216
      - USE_EXISTING_DATABASE_ACCOUNT=
      - INDEXSPACE_NAME=DM_XCHIVE_DOCBASE
      - USE_EXISTING_AEK=false
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    hostname:
      "centos7"
    container_name:
      "dctm_server_${VER}"
    ports:
      - "1489:1489"
      - "1490:1490"
      - "50000:50000"
      - "50001:50001"
      - "9080:9080"
      - "9082:9082"
      - "9081:9081"
      - "9084:9084"
      - "8081:8081"
      - "8443:8443"    
    volumes:
      - dctm_odbc:/opt/dctm/odbc
      - dctm_data:/opt/dctm/data
      - dctm_dba:/opt/dctm/dba
      - dctm_share:/opt/dctm/share
      - dctm_dfc:/opt/dctm/config
      - dctm_mdserver_conf:/opt/dctm/mdserver_conf
      - dctm_mdserver_logs:/opt/dctm/tomcat9.0.58/logs
      - dctm_Thumbnail_Server_conf:/opt/dctm/product/22.2/thumbsrv/conf
      - dctm_Thumbnail_Server_webinf:/opt/dctm/product/22.2/thumbsrv/container/webapps/thumbsrv/WEB-INF
      - dctm_MigrationUtility:/opt/dctm/product/22.2/install/external_apps/MigrationUtil
    privileged: true
#'volumes' service definition: 
volumes:
 dctm_data:
 dctm_share:
 dctm_dba:
 dctm_dfc:
 dctm_odbc:
 dctm_mdserver_conf:
 dctm_mdserver_log:
 dctm_mdserver_logs:
 dctm_Thumbnail_Server_conf:
 dctm_Thumbnail_Server_webinf:
 dctm_XhiveConnector:
 dctm_xhive_storage:
 dctm_MigrationUtility:
networks:
  default:
    external:
      name: documentum