version: '2'
services:
  da:
    user: 1001:2001
    image: registry.opentext.com/dctm-admin:22.2.0
    environment:     
     - DA_EXT_CONF=/opt/tomcat/webapps/da/external-configurations
     - PREFERPASS=webtop
     - PRESETPASS=webtop
     - OTDS_PROPERTIES=otds_url=<OTDS_APP_URL>::client_id=<OTDS_CLIENT_ID>::client_secret=<OTDS_CLIENT_SECRET>::redirect_uri=<DA_APP_URI>
     - APP_PROPERTIES=application.authentication.otds_sso.enabled=false::application.authentication.otds_sso.repo_selection_page_required=false::application.authentication.otds_sso.dm_login_ticket_timeout=250::application.language.supported_locales.locale=[en_US]::application.language.default_locale=en_US
     - DFC_PROPERTIES=dfc.data.dir=/opt/tomcat/data::dfc.tokenstorage.dir=/opt/tomcat/token::dfc.tokenstorage.enable=false::dfc.docbroker.host[0]=192.168.219.131::dfc.docbroker.port[0]=1489::dfc.globalregistry.repository=rep222::dfc.globalregistry.username=dm_bof_registry::dfc.globalregistry.password=dmadmin::dfc.session.allow_trusted_login=false::dfc.security.ssl.use_anonymous_cipher=true
    container_name:
      "dctm_admin_222"
    ports:
     - "8080:8080"
    volumes:
     - dctm_da-ext-conf:/opt/tomcat/webapps/da/external-configurations    
     - dctm_da-tomcat-logs:/opt/tomcat/logs
     - dctm_da-documentum-logs:/home/daadmin/documentum/logs
     - dctm_da-custom:/opt/tomcat/webapps/da/custom
     - dctm_da-certificate:/opt/dctm/certificate
    privileged: true
volumes:
  dctm_da-ext-conf:
  dctm_da-tomcat-logs:
  dctm_da-documentum-logs:  
  dctm_da-custom:
  dctm_da-certificate:
networks:
  default:
    external:
      name: documentum
