version: '2'
services:
  da:
    user: 1001:2001
    image: dastatelessimage
    environment:     
     - DA_EXT_CONF=/opt/tomcat/webapps/da/external-configurations
     - PREFERPASS=webtop
     - PRESETPASS=webtop
     - OTDS_PROPERTIES=otds_url=<OTDS_APP_URL>::client_id=<OTDS_CLIENT_ID>::client_secret=<OTDS_CLIENT_SECRET>::redirect_uri=<DA_APP_URI>
     - APP_PROPERTIES=application.authentication.otds_sso.enabled=false::application.authentication.otds_sso.repo_selection_page_required=false::application.authentication.otds_sso.dm_login_ticket_timeout=250::application.language.supported_locales.locale=[en_US]::application.language.default_locale=en_US
     - DFC_PROPERTIES=dfc.data.dir=<DFC_DATA_DIRECTORY>::dfc.tokenstorage.dir=<DFC_TOKENSTORAGE_DIRECTORY>::dfc.tokenstorage.enable=false::dfc.docbroker.host[0]=<DFC_DOCBROKER_HOST>::dfc.docbroker.port[0]=<DFC_DOCBROKER_PORT>::dfc.globalregistry.repository=<DFC_GLOBALREGISTRY_REPOSITORY>::dfc.globalregistry.username=<DFC_GLOBALREGISTRY_USERNAME>::dfc.globalregistry.password=<DFC_GLOBALREGISTRY_PASSWORD>::dfc.session.allow_trusted_login=false::dfc.security.ssl.use_anonymous_cipher=true
    container_name:
      "dastatelesscontainer"
    ports:
     - "APPSERVER_PORT:8080"
    volumes:
     - da-ext-conf:/opt/tomcat/webapps/da/external-configurations    
     - da-tomcat-logs:/opt/tomcat/logs
     - da-documentum-logs:/home/daadmin/documentum/logs
     - da-custom:/opt/tomcat/webapps/da/custom
     - da-certificate:/opt/dctm/certificate
    privileged: true
volumes:
  da-ext-conf:
  da-tomcat-logs:
  da-documentum-logs:  
  da-custom:
  da-certificate: